#ifndef CARDTYPES_H_
#define CARDTYPES_H_

#define DECK_SIZE_LIMIT 20

#define BASIC_CARD_LIMIT      5
#define BASIC_CARD_SET_LIMIT  10
#define BASIC_CARD_ID_START   1004
#define BASIC_CARD_ID_END     1006

#define ADV_CARD_LIMIT      2
#define ADV_CARD_SET_LIMIT  10
#define ADV_CARD_ID_START   2001
#define ADV_CARD_ID_END     2008

enum Action
{
  ATTACK_ACTION,
  DEFEND_ACTION,
  EQUIP_ACTION,
  HEAL_ACTION,
  HERO_ACTION,
  INTERRUPT_ACTION,
  SPECIAL_ACTION,
  NO_ACTION
};

enum Rarity
{
  RARITY_CORE,
  RARITY_BASIC,
  RARITY_HIGHGRADE,
  RARITY_UNIQUE,
  RARITY_HERO,
  RARITY_UNKNOWN
};

enum CardType
{
  ATTACK_TYPE,
  BLOCK_TYPE,
  HEAL_TYPE,
  GEAR_TYPE,
  HERO_TYPE,
  NO_TYPE
};

enum CardClass
{
  BERSERKER,
  NECROMANCER,
  PALADIN,
  SPECIAL,
  INTERRUPT,
  NO_CLASS
};

enum cardID
{
  CORE_ATTACK_ID = 1001,
  CORE_BLOCK_ID  = 1002,
  CORE_HEAL_ID   = 1003,

  BASIC_ATTACK_ID = 1004,
  BASIC_BLOCK_ID  = 1005,
  BASIC_HEAL_ID   = 1006,

  ADV_MIGHTY_SWING_ID  = 2001,
  ADV_DOUBLE_STRIKE_ID = 2002,
  ADV_STRIKE_HEAL_ID   = 2003,
  ADV_DOUBLE_BLOCK_ID  = 2004,
  ADV_BLOCK_STRIKE_ID  = 2005,
  ADV_BLOCK_HEAL_ID    = 2006,
  ADV_SUPER_HEAL_ID    = 2007,
  ADV_LIFE_BOOST_ID    = 2008,

  UNQ_FLASH_STRIKE_ID    = 2101,
  UNQ_FEINT_STRIKE_ID    = 2102,
  UNQ_SIDE_STEP_ID       = 2103,
  UNQ_DRAMATIC_DODGE_ID  = 2104,
  UNQ_QUICK_HEAL_ID      = 2105,
  UNQ_EMERGENCY_HEAL_ID  = 2106,
  UNQ_HEALER_BLADE_ID    = 2107,
  UNQ_POCKET_POTION_ID   = 2108,
  UNQ_VISION_WARD_ID     = 2201,
  UNQ_LEATHER_CUIRASS_ID = 2202,

  // BERSERKER
  HERO_FRENZIED_STRIKE_ID = 4001,
  HERO_RECKLESS_STRIKE_ID = 4002,
  HERO_BLOODLUST_ID       = 4003,
  HERO_RETRIBUTION_ID     = 4004,
  HERO_SPIRIT_WALKER_ID   = 4005,

  // NECROMANCER
  HERO_SOUL_RIP_ID       = 5001,
  HERO_ALCHEMY_ID        = 5002,
  HERO_RAISE_DEAD_ID     = 5003,
  HERO_POISON_GAS_ID     = 5004,
  HERO_BLOOD_IS_POWER_ID = 5005,
  
  // PALADIN
  HERO_IRON_SKIN_ID        = 6001,
  HERO_PRESS_THE_ATTACK_ID = 6002,
  HERO_BLACKSMITH_ID       = 6003,
  HERO_DIVINE_SHIELD_ID    = 6004,
  HERO_JUDGEMENT_DAY_ID    = 6005
};

#endif
